---
title: "Les Expressions réguliéres sous R"
author: "Ameline et Maude"
date: "6 septembre 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction :

### Définition
Les expressions régulières sont des **chaînes de caractères** décrivant un *motif*, un enssemble de chaînes de caractères possible, selon une syntaxe définie.  

### Exemples

en expressiosn régulières le `.` correspond a tout autres caractères donc `t.t.` peut correspondre à :

- tata
- totO
- ou  tot4 

## Normes de syntaxes
Il existes 2 types de syntaxes.

- Perl-Compatible Régular Expressions (PCRE) compatible avec le code Python
- POSIX normalisé, théoriquement plus simple, plus lente.

**R** utilise la norme **POSIX** par défaut.

(*la Norme PCRE s'utilise sur R à condition d'indiquer perl=TRUE*)

## Syntaxe POSIX
Quelques éléments de syntaxes pour les expressions régulières...

`.` tout caractère 
ex : tot. peut correspondre à toto tota totu etc...

`^` le motif qui suit le "^" est situé en début de chaine 
ex : ^man peut correspondre à mange mais pas démange

`$` le motif qui suit le "$" est situé en fin de chaine

`|` indique un motif alternatif
ex : to|ti sélectionnera to et ti en absence de to ? (à vérifier)

`?` 0 ou 1 occurence du motif
ex : ?bla sélectionnera toto et bla mais pas blabla

## Syntaxe POSIX

`*` 0 ou plusieurs occurence du motif
ex : *bla selectionnera toto ou blabla mais pas bla

`+` 1 ou plusieurs occurences du motif 
ex : +bla selectionnera bla et blabla mais pas toto

`[...]` le motif peut prendre un des caractères entre crochets
ex : t[oa]to peut correspondre à tato ou toto

`[^...]` le motif peut prendre tout les caractère a l'exeption de ceux qui sont indiquer entre crochet
ex : t[^u]to peut correspondre à toto, t4to mais pas à tuto


